# Generated by Django 4.0.6 on 2022-08-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_age_alter_account_gender_alter_account_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
    ]
