# Generated by Django 4.0.6 on 2022-08-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_account_age_alter_account_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
    ]
