# Generated by Django 4.0.6 on 2022-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
