# Generated by Django 4.1 on 2022-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_mony'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('select color please ...', 'select color please ...'), ('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('black', 'black'), ('white', 'white')], default='select color please ...', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='mony',
            field=models.CharField(choices=[('$', '$'), ('تومان', 'تومان')], default='dollers', max_length=10),
        ),
    ]
