# Generated by Django 4.1 on 2022-08-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_color_alter_product_mony'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suk',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
